spring:
    application:
        name: admin-gateway
    profiles:
        active: dev
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null

server:
    port: 8765 #启动端口

zuul:
    routes:
        back:  #  后台路由
            path: /back/**
            serviceId: admin-back

        ui:  #  前台路由
            path: /admin/**
            serviceId: admin-ui

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        lease-renewal-interval-in-seconds: 10  # 更新时间间隔，默认30，即30秒发送一次心跳
        lease-expiration-duration-in-seconds: 30 #  到期时间，默认90秒
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    eureka:
        enabled: true  # spring cloud是默认关闭Hystrix的断路器功能
gate:
    ignore:
        startWith: /static
        contain: .
    oauth:
        prefix: /api
    jwt:
        secret: Xe*g@1jda
        expiration: 7200
        header: access-token