spring:
    application:
        name: admin-gateway
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null

server:
    port: 8765 #启动端口

zuul:
    routes:
        back:  #  后台路由
            path: /back/**
            serviceId: admin-back
        ui:  #  前台路由
            path: /admin/**
            serviceId: admin-ui

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

gate:
    ignore:
        startWith: /static
        contain: .
    oauth:
        prefix: /api
    jwt:
        secret: Xe*g@1jda
        expiration: 7200
        header: access-token