logging:
    level:
        tk.mybatis: DEBUG
        com.github.dalianghe.security.admin: DEBUG

spring:
    application:
        name: gms-admin
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/ag_admin?useUnicode=true&characterEncoding=UTF8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    basepackage: com.github.dalianghe.security.admin.mapper
    xmlLocation: classpath:mapper/**/*.xml

server:
    port: 8762

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
    client:
        registerWithEureka: true  #  实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
        fetchRegistry: true  #  此客户端是否获取eureka服务器注册表上的注册信息，默认为true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/  #  Eureka注册中心地址
