spring:
    application:
        name: admin-back
    profiles:
        active: dev  # 指定环境
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource  # 使用druid数据源
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    jackson:
            date-format: yyyy-MM-dd HH:mm:ss
            time-zone: GMT+8
            default-property-inclusion: non_null

mybatis:
    basepackage: com.github.dalianghe.security.admin.mapper
    xmlLocation: classpath:mapper/**/*.xml


eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        lease-renewal-interval-in-seconds: 10  # 更新时间间隔，默认30，即30秒发送一次心跳
        lease-expiration-duration-in-seconds: 30 #  到期时间，默认90秒
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    client:
        registerWithEureka: true  #  实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
        fetchRegistry: true  #  此客户端是否获取eureka服务器注册表上的注册信息，默认为true
