server:
    port: 8762

spring:
    datasource:
        # name: test
        url: jdbc:mysql://localhost:3306/ag_admin?useUnicode=true&characterEncoding=UTF8
        username: root
        password: root

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/  #  Eureka注册中心地址

logging:
    level:
        tk.mybatis: DEBUG
        com.github.wxiaoqi.security.admin: DEBUG
